### ISSUE TITLE
no autostart option

### ISSUE THREAD

**Issue by rande** [plathrop/puppet-module-supervisor#74]
Why there is no autostart option available ?

We might want to create service but enable it on demand depends on external context.

I can create a PR if you want, but this will be a BC break with the ``ensure`` option

**Comment by plathrop** [comment]
Autostart option was recently added. See https://github.com/ox-it/puppet-module-supervisor/blob/074b506c584775d7fcf6151c3da3a809d1b64389/templates/service.ini.erb#L10
