### ISSUE TITLE
Module on puppet forge isn't up to date

### ISSUE THREAD

**Issue by Vincent--** [plathrop/puppet-module-supervisor#89]
Hey !

I almost missed your module on sourceforge as it hasn't been updated since 2 years.
It's a shame as you're the only one to propose supervisor group management...
Do you plan to refresh the version or should I use the git repo directly ?

Thanking you in advance.

Regards,
Vincent.

**Comment by plathrop** [comment]
Hi Vincent,

Although I maintain the code, I don't push the versions to the forge; I'm not sure who did originally. You should probably just use the repo.

**Comment by fungusakafungus** [comment]
I just tagged the current master and pushed it as v0.2.0 to puppet forge

**Comment by Vincent--** [comment]
Thks everybody ! :+1:
